---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-claim
spec:
  #Определяем, какое кол-во подов могут использовать диск
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
