---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: default.svc.cluster.local
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /
