#Версия api нашего приложения, можно менять при изменении
apiVersion: v1
#Тип объекта, который затрагивает наш манифест
kind: Pod
metadata:
  #имя запускаемого пода
  name: my-pod
  labels:
    app: my-app
#в этой секции описывается как именно должен выглядеть под декларативным методом
spec:
  containers:
    - image: nginx:1.12
      name: nginx
      ports:
        - containerPort: 80
